name: deep_learning_project
environments:
  default:
    - environment.yml
  # de-comment this to have a cpu environment
  # and comment environment.yml
  #   - environment-cpu.yml
variables:
  PYTHONPATH: ./
  HYDRA_FULL_ERROR: '1'
commands:
  train-gpu:
    cmd: python factor_vae/train.py accelerator=gpu devices=1
    environment: default
    variables:
  train-cpu:
    cmd: python factor_vae/train.py accelerator=cpu
    environment: default
    variables:
  compress-runs:
    cmd: compress-runs = "tar cfz saved_models.tar.gz saved_models/"
    environment: default
    variables:
  tensorboard:
    cmd: tensorboard --logdir=saved_models/
    environment: default
    variables:
  clean-empty-runs:
    cmd: "python -c '\nfrom path import Path\nfor run in Path(\"saved_models\").dirs():\n\
      \    if not run.joinpath(\"best.ckpt\").exists():\n        print(f\"Removing\
      \ {run}\")\n        run.rmtree()'\n"
    environment: default
    variables:

