channels:
  - pytorch
dependencies:
  - python=3.10
  - matplotlib
  - seaborn
  - numpy
  - pytorch
  - torchvision
  - pip:
    - pytorch-lightning
    - path
    - tensorguard
    - hydra-core
  - pytest
  - tensorboard
  - tqdm
  - cpuonly
platforms:
  - linux-64
  - win-64
