width: 28
height: 28
channels: 1
num_classes: 10
files_location: ~/.cache/torchvision_dataset
train:
  _target_: torchvision.datasets.MNIST
  root: ${dataset.files_location}
  train: true
  download: true
  transform:
    _target_: torchvision.transforms.ToTensor
val:
  _target_: torchvision.datasets.MNIST
  root: ${dataset.files_location}
  train: false
  download: true
  transform:
    _target_: torchvision.transforms.ToTensor